<div class="container">

<table style="width: 100%;"><tr>
<td>abort</td>
<td style="text-align: right;">R Documentation</td>
</tr></table>
<h2>Aborts the current expression call</h2>

<h3>Description</h3>

<p>Aborts the current expression call and returns to the top level prompt/browser
<em>without signaling a condition</em>.
</p>


<h3>Usage</h3>

<pre><code class="language-R">## Default S3 method:
abort(..., call.=TRUE, domain=NULL)
</code></pre>


<h3>Arguments</h3>

<table>
<tr style="vertical-align: top;">
<td><code>...</code></td>
<td>
<p>(optional) Objects coerced to <code>character</code> and pasted together without a separator, or a @condition object. If no object are given, no message is printed.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>call.</code></td>
<td>
<p>If <code>TRUE</code>, the call is added to the message, otherwise not.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>domain</code></td>
<td>
<p>Used to translate the message (see <code>gettext</code>()). If <code>NA</code>, messages will not be translated.</p>
</td>
</tr>
</table>
<h3>Details</h3>

<p>There are still cases where one can "catch" the abort and undo it, cf. [1].
</p>


<h3>Value</h3>

<p>Returns nothing.
</p>


<h3>Author(s)</h3>

<p>Henrik Bengtsson</p>


<h3>References</h3>

<p>[1] R-devel thread ‚Äù, Sept 11, 2012,
<a href="https://stat.ethz.ch/pipermail/r-devel/2012-September/064838.html">https://stat.ethz.ch/pipermail/r-devel/2012-September/064838.html</a>.<br></p>


<h3>See Also</h3>

<p><code>throw</code>().
<code>stop</code>().
Internally, <code>invokeRestart</code>()<code>("abort")</code> is utilized.
</p>


<h3>Examples</h3>

<pre><code class="language-R">## Not run: 
 foo &lt;- function() {
  cat("foo()...\n")
  on.exit(cat("foo()...done\n"))
  tryCatch({
    stop("Woops!")
  }, error = function(ex) {
    cat("An error was caught: ", ex$message, "\n", sep="")
  })
  cat("Continuing...\n")
}

bar &lt;- function() {
  cat("bar()...\n")
  on.exit(cat("bar()...done\n"))
  tryCatch({
    abort("Woops!")
  }, error = function(ex) {
    cat("An error was caught: ", ex$message, "\n", sep="")
  })
  cat("This message will never be displayed...\n")
}

# An error generated by stop() can be caught
foo()

# ...which is not possible when using abort()
bar()

# This expression is never reached
cat("This line will never be outputted.\n")


## End(Not run)</code></pre>


</div>